### ISSUE TITLE
Remove hardcoded dc namespace from oai driver

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#198] opened 2022-09-02 14:51 UTC
The hardcoded dc namespaces are causing non dc collections (like qnl) to fail.

https://github.com/sul-dlss/dlme-airflow/blob/main/dlme_airflow/drivers/oai_xml.py#L70-L73

**Comment by aaron-collier** [comment] 2022-09-02 15:28
@jacobthill closing as a dupe of #175 that is being worked on now.

**Closed by aaron-collier** 2022-09-02 15:28 UTC
