### ISSUE TITLE
QNL OAI server sometimes throws exceptions 

### ISSUE THREAD

**Issue by edsu** [sul-dlss/dlme-airflow#200] opened 2022-09-02 21:53 UTC
Here's a screen shot of an error from QNL's OAI-PMH server:

<img width="1662" alt="Screen Shot 2022-09-02 at 5 50 12 PM" src="https://user-images.githubusercontent.com/33829/188239783-e9eeb914-be2f-4df2-906d-47c7e06f527d.png">

I've noticed that you can generate these programmatically using Sickle to just walk through the records that come back from a ListRecords call. It doesn't seem to be deterministic when the errors get thrown. Perhaps we can put a sleep in between requests to be gentler? Or maybe there's a fix they can do on their side?

```python
import sickle

oai = sickle.Sickle("https://api.qdl.qa/api/oaipmh")
for rec in oai.ListRecords(metadataPrefix="mods_no_ocr"):
    print(rec.header)
```

**Comment by jacobthill** [comment] 2022-09-07 13:06
@edsu, I have contacted one of their developers (Arif Shaon) and invited him to take a look at this ticket and help us come up with a strategy for solving this issue.

**Comment by aaron-collier** [comment] 2022-09-07 16:14
@jacobthill I'm assigning this to you for now pending the results of your comment above and any information from Arif. Once we have more information, we can resolve or write more tickets.

**Comment by edsu** [comment] 2022-09-14 12:17
@jacobthill if it would be helpful for Arif to chat about this problem and how to reproduce let me know, I'd be happy to do a call.

**Comment by jacobthill** [comment] 2022-09-14 13:55
I don't think QNL has made any changes; at least they haven't told me of any. This is pretty typical behavior from my experience. Sometimes collections will complete and sometime the server will throw an error. I reminded Arif of this issue so hopefully we'll here back soon but I'm hoping if we improve our http request retries and data partners do what they can, we will see this issue a lot less.

**Comment by edsu** [comment] 2022-09-14 20:46
I ran the script above using Sickle to iterate through all the responses. It ran for a little over two hours, found 44,570 records, but died with this exception about the resumption token being invalid:

```
Traceback (most recent call last):
  File "/Users/edsummers/Projects/sul-dlss/dlme-airflow/qnl.py", line 5, in <module>
    for rec in oai.ListRecords(metadataPrefix="mods_no_ocr"):
  File "/Users/edsummers/Library/Caches/pypoetry/virtualenvs/dlme-airflow-4uPLCoq4-py3.10/lib/python3.10/site-packages/sickle/iterator.py", line 52, in __next__
    return self.next()
  File "/Users/edsummers/Library/Caches/pypoetry/virtualenvs/dlme-airflow-4uPLCoq4-py3.10/lib/python3.10/site-packages/sickle/iterator.py", line 151, in next
    self._next_response()
  File "/Users/edsummers/Library/Caches/pypoetry/virtualenvs/dlme-airflow-4uPLCoq4-py3.10/lib/python3.10/site-packages/sickle/iterator.py", line 138, in _next_response
    super(OAIItemIterator, self)._next_response()
  File "/Users/edsummers/Library/Caches/pypoetry/virtualenvs/dlme-airflow-4uPLCoq4-py3.10/lib/python3.10/site-packages/sickle/iterator.py", line 91, in _next_response
    raise getattr(
sickle.oaiexceptions.BadResumptionToken: The value of the resumptionToken argument is invalid or expired.
```

**Comment by arifshaon** [comment] 2022-09-18 11:00
Apologies for the delay in replying.  I have had our IT look into this issue and they have discovered that this is caused by the low threshold (1000 requests per 30 mins) set for the no. of HTTP requests to the OAI-PMH Azure function. Unfortunately, they cannot increase the threshold as it has cost implications. So, they have advised to add a minimum 2 sec delay between every HTTP GET request from the same IP address.  Please let me know if that solves the problem.

**Comment by edsu** [comment] 2022-09-19 15:06
Just fyi, adding a sleep timer to our OAI intake driver, and allowing it to be configured in the Collection YAML should be relatively easy.

**Comment by arifshaon** [comment] 2022-09-20 05:00
Hi @jacobthill - as far as I understand from our IT infrastructure guys, the HTTP GET requests to the OAI-PMH app are throttled at 1000 per 30 mins. This is not 1000 metadata records in OAI-PMH ListRecords response but 1000 HTTP GET requests to the app. For example, if you submit 999 ListRecords verbs followed by 2 Identify verbs within a 30 min period, the 2nd identify request may be throttled. Hope this helps.

**Closed** 2022-09-20 19:41 UTC
