### ISSUE TITLE
Write to csv in batches instead of storing all records in memory

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#124] opened 2022-04-07 17:29 UTC
As the DLME data manager, I only need a sample of the data set of a given provider to write the traject config. Sometimes larger sets fail when harvesting locally and since nothing is written to csv, the whole process must be run again. Writing to csv in batches would enable me to stop a process when all I need is a sample to write the config file. It could also help with the out of memory issues larger data sets cause https://github.com/sul-dlss/dlme-airflow/issues/123.

**Comment by aaron-collier** [comment] 2022-08-25 20:41
https://github.com/sul-dlss/dlme-airflow/blob/508aaa073d3d9732ad4c584cbfe58025092bef04/dlme_airflow/utils/dataframe.py#L22 is where we write the csv data. 

The write `to_csv` is out of the box Intake, so we need to determine if we can provide a chunk size to write at a time and append to the file for both local development failure testing and part of performance tuning.

**Comment by edsu** [comment] 2022-08-25 22:32
Is it possible to get a stack trace for when the harvest fails for memory reasons?

**Comment by edsu** [comment] 2022-08-29 18:06
I think that the problem isn't the write so much as the reading? intake does use [dask](https://www.dask.org/) which seems to have some knobs for tuning how things are read in. If we can reproduce the problem reliably I think that'll help us figure out how to figure out what the problem is?

**Comment by aaron-collier** [comment] 2022-08-29 19:57
Yeah, this is a tough one to track down because if the task fails we lose the logs (upstream, locally the dev log should be usable)... so we may be able to get to the bottom of it soon.

**Comment by edsu** [comment] 2022-09-06 16:21
Would a way of triggering it locally be to just start a ton of workflows at once? Or is there a particular workflow that does it?

**Comment by edsu** [comment] 2022-09-06 21:30
I synced the metadata to my workstation:

```
aws s3 cp s3://dlme-metadata-dev/metadata metadata --recursive
```

Then I wrote a program to load all the CSVs in to RAM on my workstation and calculated the amount of memory used which came to 0.4 GB. Are we sure that things are blowing up during harvest? If I'm reading the right CSVs this may point to another memory issue problem during harvesting?

**Comment by edsu** [comment] 2022-09-14 12:02
I think that the motivation for this issue has now been resolved by #205.

**Closed by edsu** 2022-09-14 12:02 UTC
